
project: "tcl"
name: "tinyimagenet-tcl-seed0-0.00001"
method: "tcl"
method_kwargs:
  entropy_weight: 5.0
pretext:
  enable: True
  dir: /nas/cjh/solo-learn/trained_models/mocov2plus/rjfbda9n
  ckpt: mocov2plus-tinyimagenet-2-rjfbda9n-ep=999.ckpt

tcl_checkpoint: save/tinyimagenet/tinyimagenet-tcl-seed0-0.00001/checkpoint.pth.tar

backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 200
  feat_dim: 128
  temperature: 1
data:
  dataset: tinyimagenet
  train_path: "/nas/datasets/tiny-imagenet-200/train" #
  val_path: "/nas/datasets/tiny-imagenet-200/val/images_new" #
  num_workers: 8

  split: 'train'

dist_on_itp: False
dist_eval: False
dist_url: "env://"

optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.00001
  kwargs:
    weight_decay: 0.0001

scheduler:
  name: constant

criterion:
  name: tcl
  ins_temp: 0.5
  clu_temp: 1.0
max_epochs: 1000

cluster_eval:
  plot_freq: 10
  plot_title: 'tcl'
  eval_freq: 2

  select_enable: True
  select_freq: 5
  select_conf: 0.99


augmentation_strong:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]