
project: "cc_v1"
#name: "cifar20-cc-1"
name: "cifar20-cc-all"
method: "cc"
method_kwargs:
  entropy_loss_weight: 1.0

pretext:
  enable: True
#  dir: ./trained_models/mocov2plus/repo0z7z
#  ckpt: mocov2plus-cifar20-2-repo0z7z-ep=999.ckpt
  dir: ./trained_models/mocov2plus/k1m25ecy
  ckpt: mocov2plus-cifar20-all-k1m25ecy-ep=999.ckpt
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 20
  feat_dim: 128
data:
  dataset: cifar20
  train_path: "../../datasets" #
  val_path: "../../datasets" #
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.00005
  kwargs:
    weight_decay: 0.0000
scheduler:
  name: constant

criterion:
  name: cc
  instance_temperature: 0.5
  cluster_temperature: 1.0
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'CC'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.5071, 0.4865, 0.4409]
    std: [0.2673, 0.2564, 0.2762]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.5071, 0.4865, 0.4409]
    std: [0.2673, 0.2564, 0.2762]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.5071, 0.4865, 0.4409]
    std: [0.2673, 0.2564, 0.2762]