
project: "scan_v2"
#name: "cifar10-scan3-v2-1"
name: "cifar10-scan3-noprun-seed0"
method: "scan"
method_kwargs:
  threshold: 0.99
  apply_class_balancing: True
pretext:
  enable: True
  dir: save/scan/cifar10/cifar10-scan2-noprun-seed0
  ckpt: checkpoint.pth.tar
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
data:
  dataset: cifar10
  train_path: "/nas/datasets" #
  val_path: "/nas/datasets" #
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 1000
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 100

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]