
project: "scan_v2"
#name: "cifar10-scan2-f2"
name: "cifar10-scan2-all-seed3"
method: "scan"
method_kwargs:
  entropy_weight: 5.0
pretext:
  enable: True
#  dir: ./trained_models/mocov2plus/x53fb4bu
#  ckpt: mocov2plus-cifar10-2-x53fb4bu-ep=999.ckpt
  dir: ./trained_models/mocov2plus/x53fb4bu
  ckpt: mocov2plus-cifar10-2-x53fb4bu-ep=999.ckpt
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
  feat_dim: 512
  temperature: 1
data:
  dataset: cifar10
  train_path: "../../datasets" #
  val_path: "../../datasets" #
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  num_neighbors: 20
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 50

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]