
project: "scan_v1"
name: "cifar10-scan2-1"
method: "scan"
method_kwargs:
  entropy_weight: 5.0
pretext:
  enable: True
  dir: trained_models/mocov2plus/kb44zdxw
  ckpt: mocov2plus-cifar10-2-kb44zdxw-ep=999.ckpt

backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
  feat_dim: 512
  temperature: 1

scan2_checkpoint: save/scan/cifar10/cifar10-scan2-1/checkpoint.pth.tar
best_checkpoint: save/scan/cifar10/cifar10-scan2-1/best_model.pth.tar
scan2_dir: save/scan/cifar10/cifar10-scan2-1/

data:
  dataset: cifar10
  train_path: "/nas/datasets" #
  val_path: "/nas/datasets" #
  num_workers: 8
  split: 'train+test'
  num_neighbors: 20
  partial: False #partial_rate:

optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 100

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 5

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]