
project: "cdc"
name: "Office-31-dw-seed0"
method: "cdcv2"
method_kwargs:
  per_class_selected_num: 50
  super_cluster_num: 150
  w_en: 1.0
pretext:
  enable: True
  dir: trained_models/mocov2plus/9b1e8kdp
  ckpt: mocov2plus-Office-31-D-9b1e8kdp-ep=999.ckpt
backbone:
  name: "resnet50"
  nheads: 1
  nclusters: 31
  feat_dim: 512
data:
  dataset: Office-31
  train_path: "/nas/datasets/Office-31/dslr" #
  val_path: "/nas/datasets/Office-31/webcam" #
  num_workers: 8
  split: 'train'

optimizer:
  name: "adam"
  batch_size: 500
  sub_batch_size: 250
  lr: 0.0001
  kwargs:
    weight_decay: 0.000

scheduler:
  name: constant
max_epochs: 200
cluster_eval:
  plot_freq: 10
  plot_title: 'CDC'
  eval_freq: 5
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
