
project: "cc_v0"
name: "cifar10-cc-4"
method: "cc"
method_kwargs:
  entropy_loss_weight: 1.0

cc_checkpoint: save/cifar10/cc/cc_checkpoint.pth
cc_dir: save/cifar10/cc/pic
pretext:
  enable: True
  dir: /nas/cjh/solo-learn/trained_models/mocov2plus/kb44zdxw
  ckpt: mocov2plus-cifar10-2-kb44zdxw-ep=999.ckpt
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
  feat_dim: 128
data:
  dataset: cifar10
  train_path: "/nas/datasets" #  "../CDC/data/cifar10"
  val_path: "/nas/datasets" #  "../CDC/data/cifar10"
  num_workers: 8
  split: 'train'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.00005
  elr: 0.00005
  kwargs:
    weight_decay: 0.0000
scheduler:
  name: constant

criterion:
  name: cc
  instance_temperature: 0.5
  cluster_temperature: 1.0
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'CC'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99

augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]