
project: "cdc"
name: "tinyimagenet-res18-a20-t1-seed5"
method: "cdcv2"
method_kwargs:
  per_class_selected_num: 25
  super_cluster_num: 1000
  w_en: 1.0

pretext:
  enable: True
  dir: trained_models/mocov2plus/hsyb3nis
  ckpt: mocov2plus-tinyimagenet-1-hsyb3nis-ep=999.ckpt

alpha: 2.0
t: 0.1

backbone:
  name: "resnet18"
  nheads: 1
  nclusters: 200
  feat_dim: 512
data:
  dataset: tinyimagenet
  train_path: "/nas/datasets/tiny-imagenet-200/train"
  val_path: "/nas/datasets/tiny-imagenet-200/train"
  num_workers: 8
  split: 'train+test'
optimizer:
  name: "adam"
  batch_size: 5000
  sub_batch_size: 1000
  lr: 0.00005
  kwargs:
    weight_decay: 0.000
scheduler:
  name: constant
max_epochs: 100
cluster_eval:
  plot_freq: 10
  plot_title: 'CDC'
  eval_freq: 5
augmentation_strong:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

