
project: "scan_v2"
#name: "tinyimagenet-scan3-v2-1"
name: "tinyimagenet-scan3-v2-all-seed3"
method: "scan"
method_kwargs:
  threshold: 0.8
  apply_class_balancing: True
pretext:
  enable: True
#  dir: ./trained_models/scan/tinyimagenet/tinyimagenet-scan2-f2
  dir: ./trained_models/scan/tinyimagenet/tinyimagenet-scan2-f2-seed3
  ckpt: checkpoint.pth.tar
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 200
data:
  dataset: tinyimagenet
  train_path: "../../datasets/tiny-imagenet-200/train" #  "../CDC/data/cifar10"
  val_path: "../../datasets/tiny-imagenet-200/train" #  "../CDC/data/cifar10"
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 1000
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.95
augmentation_strong:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
