
project: "scan_v2"
name: "tinyimagenet-scan2-noprun-seed0"
method: "scan"
method_kwargs:
  entropy_weight: 5.0

back_epoch: 0

pretext:
  enable: True
  dir: trained_models/mocov2plus/rjfbda9n
  ckpt: mocov2plus-tinyimagenet-2-rjfbda9n-ep=999.ckpt

#scan_checkpoint: save/scan/tinyimagenet/tinyimagenet-scan-noprun-seed0/checkpoint.pth.tar
#scan_dir: save/scan/tinyimagenet/tinyimagenet-scan-noprun-seed0

backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 200
  feat_dim: 512
  temperature: 1
data:
  dataset: tinyimagenet
  train_path: "/nas/datasets/tiny-imagenet-200/train" #  "../CDC/data/cifar10"
  val_path: "/nas/datasets/tiny-imagenet-200/val/images_new" #  "../CDC/data/cifar10"
  num_workers: 8
  split: 'train'
  num_neighbors: 20
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 100

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 64
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
