
project: "scan_v2"
#name: "imagenet10-scan3-v2-1"
name: "imagenet10-scan3-longtail-seed6"
method: "scan"
method_kwargs:
  threshold: 0.99
  apply_class_balancing: True
pretext:
  enable: True
  dir: save/scan/imagenet10/imagenet10-scan2-longtail-seed6
  ckpt: best_model.pth.tar
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
data:
  dataset: imagenet10
  train_path: "/nas/datasets/imagenet10"
  val_path: "/nas/datasets/imagenet10"
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

