
project: "scan_v2"
#name: "cifar20-scan3-v2-1"
name: "cifar20-scan3-longtail-seed5"
method: "scan"
method_kwargs:
  threshold: 0.99
  apply_class_balancing: True
pretext:
  enable: True
  dir: save/scan/cifar20/cifar20-scan2-longtail-seed5
  ckpt: best_model.pth.tar
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 20
data:
  dataset: cifar20
  train_path: "/nas/datasets" #
  val_path: "/nas/datasets" #
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 1000
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.5071, 0.4865, 0.4409]
    std: [0.2673, 0.2564, 0.2762]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.5071, 0.4865, 0.4409]
    std: [0.2673, 0.2564, 0.2762]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.5071, 0.4865, 0.4409]
    std: [0.2673, 0.2564, 0.2762]