
project: "cdc"
name: "waterbirds-cdc-seed5"
method: "cdcv2"
method_kwargs:
  per_class_selected_num: 150
  super_cluster_num: 20
  w_en: 1.0
pretext:
  enable: True
  dir: trained_models/mocov2plus/m0icul14
  ckpt: mocov2plus-waterbirds-m0icul14-ep=999.ckpt

back_epoch: 0

backbone:
  name: "resnet50"
  nheads: 1
  nclusters: 2
  feat_dim: 512
data:
  dataset: waterbirds
  train_path: "/nas/datasets/waterbirds/waterbird_complete95_forest2water2" #
  val_path: "/nas/datasets/waterbirds/waterbird_complete95_forest2water2" #
  num_workers: 8
  split: 'train'

optimizer:
  name: "adam"
  batch_size: 256
  sub_batch_size: 125
  lr: 0.0001
  kwargs:
    weight_decay: 0.000
scheduler:
  name: constant
max_epochs: 40
cluster_eval:
  plot_freq: 10
  plot_title: 'CDC'
  eval_freq: 1
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
