
project: "tcl-osr"
name: "cifar10-tcl-osr-nopre-seed1"
method: "tcl"
method_kwargs:
  entropy_weight: 5.0
pretext:
  enable: False
  dir: /nas/cjh/solo-learn/trained_models/mocov2plus/kb44zdxw
  ckpt: mocov2plus-cifar10-2-kb44zdxw-ep=999.ckpt

tcl_checkpoint: save/tcl_osr/cifar10/cifar10-tcl-osr-nopre-seed1/checkpoint.pth.tar
best_checkpoint: save/tcl_osr/cifar10/cifar10-tcl-osr-nopre-seed1/best_model.pth.tar
save_plot: save/tcl_osr/cifar10/cifar10-tcl-osr-nopre-seed1/

known: [1,2,4,5,6,7]
#known: [0,1,2,3,4,5,6,7,8,9]

backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 6
  feat_dim: 128
  temperature: 1
data:
  dataset: cifar10
  train_path: "/nas/datasets" #
  val_path: "/nas/datasets" #
  num_workers: 8

  split: 'train+test'

optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.00001
  kwargs:
    weight_decay: 0.0001

scheduler:
  name: constant

criterion:
  name: tcl
  ins_temp: 0.5
  clu_temp: 1.0
max_epochs: 1000

cluster_eval:
  plot_freq: 20
  plot_title: 'tcl'
  eval_freq: 10

  select_enable: True
  select_freq: 5
  select_conf: 0.99

augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True

augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]

augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]