
project: "cdc"
name: "imagenet10-s50-c150-lr0001-bs1000-su125-seed2"
method: "cdcv2"
method_kwargs:
  per_class_selected_num: 50
  super_cluster_num: 150
  w_en: 1.0
pretext:
  enable: True
  dir: trained_models/mocov2plus/1aojbpyy
  ckpt: mocov2plus-imagenet10-2-1aojbpyy-ep=999.ckpt

back_epoch: 0

backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
  feat_dim: 512
data:
  dataset: imagenet10
  train_path: "/nas/datasets/imagenet10"
  val_path: "/nas/datasets/imagenet10"
  num_workers: 8
  split: 'train+test'
optimizer:
  name: "adam"
  batch_size: 1000
  sub_batch_size: 125
  lr: 0.0001
  kwargs:
    weight_decay: 0.000
scheduler:
  name: constant
max_epochs: 100
cluster_eval:
  plot_freq: 10
  plot_title: 'CDC'
  eval_freq: 1
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
