
project: "cc_v1"
name: "imagenet10-cc-1-seed1"
method: "cc"
method_kwargs:
  entropy_loss_weight: 1.0

pretext:
  enable: True
  dir: ./trained_models/mocov2plus/1aojbpyy
  ckpt: mocov2plus-imagenet10-2-1aojbpyy-ep=999.ckpt
backbone: 
  name: "resnet34"
  nheads: 1
  nclusters: 10
  feat_dim: 128
data:
  dataset: imagenet10
  train_path: "../../datasets/imagenet10"
  val_path: "../../datasets/imagenet10"
  num_workers: 8
  split: 'train'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.00005
  kwargs:
    weight_decay: 0.0000
scheduler:
  name: constant

criterion:
  name: cc
  instance_temperature: 0.5
  cluster_temperature: 1.0
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'CC'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

