
project: "cdc"
name: "cifar10-iniv2.1-10100-pseudo-w10-s10-k70-u10-v3-seed5"
method: "cdcv2"
method_kwargs:
  per_class_selected_num: 100
  super_cluster_num: 500
  w_en: 1.0
pretext:
  enable: True
  dir: trained_models/mocov2plus/kb44zdxw
  ckpt: mocov2plus-cifar10-2-kb44zdxw-ep=999.ckpt

back_epoch: 0


window_size: 10
start_epoch: 10
keep_ratio: 0.7
update: 10

backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 10
  feat_dim: 512
data:
  dataset: cifar10
  train_path: "/nas/datasets"
  val_path: "/nas/datasets"
  num_workers: 8
  split: 'train+test'
optimizer:
  name: "adam"
  batch_size: 1000
  sub_batch_size: 500
  lr: 0.0001
  elr: 0.00005
  kwargs:
    weight_decay: 0.000
scheduler:
  name: constant
max_epochs: 100
cluster_eval:
  plot_freq: 10
  plot_title: 'CDC'
  eval_freq: 1
augmentation_strong:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 16
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
augmentation_val:
  crop_size: 32
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]