
project: "scan_v2"
#name: "imagenetdogs-scan3-v2-1"
name: "imagenetdogs-scan3-v2-all-seed1"
method: "scan"
method_kwargs:
  threshold: 0.99
  apply_class_balancing: True
pretext:
  enable: True
#  dir: ./trained_models/scan/imagenetdogs/imagenetdogs-scan2-f2
  dir: ./trained_models/scan/imagenetdogs/imagenetdogs-scan2-f2-seed1
  ckpt: checkpoint.pth.tar
backbone:
  name: "resnet34"
  nheads: 1
  nclusters: 15
data:
  dataset: imagenetdogs
  train_path: "../../datasets/imagenetdogs" #  "../CDC/data/cifar10"
  val_path: "../../datasets/imagenetdogs" #  "../CDC/data/cifar10"
  num_workers: 8
#  split: 'train'
  split: 'train+test'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
scheduler:
  name: constant

criterion:
  name: scan
max_epochs: 100

cluster_eval:
  plot_freq: 10
  plot_title: 'SCAN'
  eval_freq: 1

  select_enable: True
  select_freq: 5
  select_conf: 0.99
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
