project: "sup_test"
name: "waterbirds-su-seed0"
method: "su"

pretext:
  enable: True
  dir: trained_models/mocov2plus/m0icul14
  ckpt: mocov2plus-waterbirds-m0icul14-ep=999.ckpt

supervised_checkpoint: save/su/waterbirds/waterbirds-su-seed0/checkpoint.pth.tar
best_checkpoint: save/su/waterbirds/waterbirds-su-seed0/best_model.pth.tar
supervised_dir: save/su/waterbirds/waterbirds-su-seed0/

scheduler:
  name: constant

backbone:
  name: "resnet50"
  nheads: 1
  nclusters: 2
  feat_dim: 128
max_epochs: 200
data:
  dataset: waterbirds
  train_path: "/nas/datasets/waterbirds/waterbird_complete95_forest2water2" #
  val_path: "/nas/datasets/waterbirds/waterbird_complete95_forest2water2" #
  num_workers: 8
  split: 'train'
  partial: False #partial_rate:
optimizer:
  name: "adam"
  batch_size: 128
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001
criterion:
  name: cc
  ins_temp: 0.5
  clu_temp: 1.0
cluster_eval:
  plot_freq: 25
  plot_title: 'SUP'
  eval_freq: 2

  select_enable: True
  select_freq: 5
  select_conf: 0.99
  
augmentation_strong:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 32
    random: True
augmentation_stantard:
  random_resized_crop:
    size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
augmentation_val:
  crop_size: 224
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]