
project: "tcl"
name: "cmnist-tcl-seed0"
method: "tcl"
method_kwargs:
  entropy_weight: 5.0
  
pretext:
  enable: True
  dir: /nas/cjh/solo-learn/trained_models/mocov2plus/kb44zdxw
  ckpt: mocov2plus-cifar10-2-kb44zdxw-ep=999.ckpt

tcl_checkpoint: save/cmnist/cmnist-tcl-seed0/checkpoint.pth.tar
best_checkpoint: save/cmnist/cmnist-tcl-seed0/best_model.pth.tar
tcl_dir: save/cmnist/cmnist-tcl-seed0/

backbone:
  name: "resnet18"
  nheads: 1
  nclusters: 2
  feat_dim: 128
  temperature: 1
  
data:
  dataset: cmnist
  train_path: "/nas/datasets/cmnist/colorized-MNIST/training.h5" #
  val_path: "/nas/datasets/cmnist/colorized-MNIST/testing.h5" #
  num_workers: 8

  split: 'train'

optimizer:
  name: "adam"
  batch_size: 256
  lr: 0.0001
  kwargs:
    weight_decay: 0.0001

scheduler:
  name: constant

criterion:
  name: tcl
  ins_temp: 0.5
  clu_temp: 1.0
max_epochs: 200

cluster_eval:
  plot_freq: 10
  plot_title: 'tcl'
  eval_freq: 2

  select_enable: True
  select_freq: 5
  select_conf: 0.999

augmentation_strong:
  crop_size: 28  # 修改为28以适应MNIST的图像大小
  normalize:
    mean: [0.5]  # MNIST一般使用0.5归一化
    std: [0.5]   # MNIST一般使用0.5归一化
  num_strong_augs: 4
  cutout_kwargs:
    n_holes: 1
    length: 8  # 根据数据集特征调整hole的大小
    random: True

augmentation_stantard:
  random_resized_crop:
    size: 28  # 修改为28
  normalize:
    mean: [0.5]
    std: [0.5]

augmentation_val:
  crop_size: 28  # 修改为28
  normalize:
    mean: [0.5]
    std: [0.5]